apiVersion: 1
groups:
  - orgId: 1
    name: topaz
    folder: Demo
    interval: 5m
    rules:
      - uid: adrr3e19t5iwwc
        title: adservice warn
        condition: B
        data:
          - refId: A
            queryType: range
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P8E80F9AEF21F6940
            model:
              datasource:
                type: loki
                uid: P8E80F9AEF21F6940
              editorMode: code
              expr: count_over_time({exporter="OTLP", job="adservice", level="WARN"} |= `` [$__auto])
              intervalMs: 1000
              maxDataPoints: 43200
              maxLines: 500
              queryType: range
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          description: ""
          runbook_url: ""
          summary: ""
        labels:
          "": ""
        isPaused: false
