# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    name: Opsgenie
    receivers:
      # <string, required> unique identifier for the receiver. Should not exceed 40 symbols. Only letters, numbers, - (hyphen), and _ (underscore) allowed.
      - type: opsgenie
        uid: opsgenie-1
        settings:
          apiKey: ${OPSGENIE_API_KEY}
          apiUrl: https://api.opsgenie.com/v2/alerts
          message: |
            {{ template "default.title" . }}
          description: some descriptive description
  - orgId: 1
    name: PagerDuty
    receivers:
      - uid: ddrpnfnwtwl4xf
        type: pagerduty
        settings:
          integrationKey: ${PAGERDUTY_API_KEY}
        disableResolveMessage: false
